---
#Used to gather device information from a defined router - Requires the router host name
- name: gather information from routers
  hosts: rtr2
  gather_facts: no

#Used to generate a banner appearing on router login - Enter the desired message in the text field 
  tasks:
      - name: Configure the login banner
        cisco.ios.ios_banner:
          banner: login
          text: |
            This is my Super cool Banner
            Written by Mark Carreira
            bottom text
          state: present

#Used to change the hostname of the specified router - Enter desired hostname in hostname field 
      - name: Change Hostname
        cisco.ios.ios_hostname:
          config:
            hostname: Router2MC
          state: merged

#Used to test simple NTP config - Provide ip address in command field
      - name: Change NTP
        cisco.ios.ios_config:
          commands:
          - ntp server 8.8.8.8

#Used to gather device configuration
      - name: Gather listed logging config
        cisco.ios.ios_logging_global:
          state: gathered

#Enables device logging
      - name: enable logging to all
        cisco.ios.ios_logging:
          dest: on

#Used to configure a loopback address on the defined host. Provide address and interface value in fields below
      - name: Set loopback IPv4 address
        cisco.ios.ios_l3_interface:
          name: loopback0
          ipv4: 1.1.1.1/32

#Provides sample OSPF host configuration. Various configuration options available: Cost, Priority, Area ID. Requires Interface value. Ipv4 and Ipv6      
      - name: Merge provided OSPF Interfaces configuration
        cisco.ios.ios_ospf_interfaces:
          config:
            - name: GigabitEthernet1
              address_family:
                - afi: ipv4
                  process:
                    id: 10
                    area_id: 0
                  adjacency: true
                  bfd: true
                  cost:
                    interface_cost: 5
                  dead_interval:
                    time: 5
                  demand_circuit:
                    ignore: true
                  network:
                    broadcast: true
                  priority: 25
                  resync_timeout: 10
                  shutdown: true
                  ttl_security:
                    hops: 50
                - afi: ipv6
                  process:
                    id: 35
                    area_id: 0
                  adjacency: true
                  database_filter: true
                  manet:
                    link_metrics:
                      cost_threshold: 10
                  priority: 55
                  transmit_delay: 45
          state: merged

#Sample SNMP Configuration - Provide ID, host, and port values
      - name: Apply the SNMP configuration
        cisco.ios.ios_snmp_server:
          config:
            communities:
            -   acl_v4: testACL
                name: mergedComm
                rw: true
            contact: contact updated using merged
            engine_id:
            -   id: AB0C5342FF0F
                remote:
                    host: 172.26.192.4
                    udp_port: 25
          state: merged

#Configuration for name servers - Requires address values for defined host           
      - name: configure name servers
        cisco.ios.ios_system:
          name_servers:
          - 8.8.8.8
          - 8.8.4.4