---
- name: gather information from routers
  hosts: rtr2
  gather_facts: no

  tasks:
      - name: Configure the login banner
        cisco.ios.ios_banner:
          banner: login
          text: |
            This is my Super cool Banner
            Written by Mark Carreira
            bottom text
          state: present

      - name: Change Hostname
        cisco.ios.ios_hostname:
          config:
            hostname: Router2MC
          state: merged

      - name: Change NTP
        cisco.ios.ios_config:
          commands:
          - ntp server 8.8.8.8

      - name: Gather listed logging config
        cisco.ios.ios_logging_global:
          state: gathered

      - name: enable logging to all
        cisco.ios.ios_logging:
          dest: on

      - name: Set loopback IPv4 address
        cisco.ios.ios_l3_interface:
          name: loopback0
          ipv4: 1.1.1.1/32
      
      - name: Merge provided OSPF Interfaces configuration
        cisco.ios.ios_ospf_interfaces:
          config:
            - name: GigabitEthernet1
              address_family:
                - afi: ipv4
                  process:
                    id: 10
                    area_id: 0
                  adjacency: true
                  bfd: true
                  cost:
                    interface_cost: 5
                  dead_interval:
                    time: 5
                  demand_circuit:
                    ignore: true
                  network:
                    broadcast: true
                  priority: 25
                  resync_timeout: 10
                  shutdown: true
                  ttl_security:
                    hops: 50
                - afi: ipv6
                  process:
                    id: 35
                    area_id: 0
                  adjacency: true
                  database_filter: true
                  manet:
                    link_metrics:
                      cost_threshold: 10
                  priority: 55
                  transmit_delay: 45
          state: merged

      - name: Apply the SNMP configuration
        cisco.ios.ios_snmp_server:
          config:
            communities:
            -   acl_v4: testACL
                name: mergedComm
                rw: true
            contact: contact updated using merged
            engine_id:
            -   id: AB0C5342FF0F
                remote:
                    host: 172.26.192.4
                    udp_port: 25
          state: merged
          
      - name: configure name servers
        cisco.ios.ios_system:
          name_servers:
          - 8.8.8.8
          - 8.8.4.4