---
#Used to pull router information from defined hosts
- name: gather information from routers
  hosts: cisco
  gather_facts: no

  tasks:
#Used to Gather fact information from host   
      - name: Gather all legacy facts
        cisco.ios.ios_facts:
          gather_subset: all

# Displays Model number in message format. Format adjustable in msg field         
      - name: Display Model number 
        debug:
          msg: "The IOS model is {{ansible_net_model}}"

# Displays Hostname information in message format. Format adjustable in msg field         
      - name: Display Switch hostname
        debug:
          msg: "The Hostname of the switch is {{ansible_net_hostname}}"

# Displays Management interface in message format. Format adjustable in msg field  
      - name: Get Management Interface
        debug:
          msg: "The management interface is {{ansible_net_interfaces.GigabitEthernet1}} and the ip address is {{ansible_net_interfaces.GigabitEthernet1.ipv4}}. The status of this interface is {{ansible_net_interfaces.GigabitEthernet1.lineprotocol}}"

# Displays Mac Address information in message format. Format adjustable in msg field. Interface must be defined in MSG field  
      - name: Get Mac Address
        debug:
          msg: "The mac address for Gig 1 is {{ansible_net_interfaces.GigabitEthernet1.macaddress}}"      

 