---
- name: gather information from routers
  hosts: cisco
  gather_facts: no

  tasks:
      - name: Gather all legacy facts
        cisco.ios.ios_facts:
          gather_subset: all
      - name: Display Model number 
        debug:
          msg: "The IOS model is {{ansible_net_model}}"
      - name: Display Switch hostname
        debug:
          msg: "The Hostname of the switch is {{ansible_net_hostname}}"
      - name: Get Management Interface
        debug:
          msg: "The management interface is {{ansible_net_interfaces.GigabitEthernet1}} and the ip address is {{ansible_net_interfaces.GigabitEthernet1.ipv4}}. The status of this interface is {{ansible_net_interfaces.GigabitEthernet1.lineprotocol}}"  
      - name: Get Mac Address
        debug:
          msg: "The mac address for Gig 1 is {{ansible_net_interfaces.GigabitEthernet1.macaddress}}"      